version: "3.8"
services:
  operador:
    container_name: operador-api
    build: .
    ports:
      - "7000:5000"
    volumes:
      - ./src:/code/src
      - ./server.py:/code/server.py
    restart: on-failure
